#!/usr/bin/with-contenv sh

echo '
-------------------------------------
Checking folder ownership...
-------------------------------------'

if [ $(stat -c '%U' /nut/titles) != "nut" ]; then
  echo "WARNING: /nut/titles is not owned by user nut ($(id -u nut)), it is owned by $(stat -c '%U (%u)' /nut/titles), nut might not have permission to read or write to this folder!"
fi

if [ $(stat -c '%U' /nut/conf) != "nut" ]; then
  echo "WARNING: /nut/conf is not owned by user nut ($(id -u nut)), it is owned by $(stat -c '%U (%u)' /nut/conf), nut might not have permission to read or write to this folder!"
fi

if [ $(stat -c '%U' /nut/_NSPOUT) != "nut" ]; then
  echo "WARNING: /nut/_NSPOUT is not owned by user nut ($(id -u nut)), it is owned by $(stat -c '%U (%u)' /nut/_NSPOUT), nut might not have permission to read or write to this folder!"
fi

echo "Done checking folder ownership..."

echo '
-------------------------------------
'